#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "config.h"
#include "follow_line.c"
#include "compass.c"

task main() {
  calibrateLight();
  calibrateCompass();

  FollowLineTilEnd();
  motor[left] = 0;
  motor[right] = 0;
  nxtDisplayCenteredTextLine(3, "Segment end");
  wait10Msec(1000);
}
