#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "follow_line.c"
#include "compass.c"

task main() {
  calibrateLight();
  calibrateCompass();

  int found = FollowSegmentTilEnd();
  motor[left] = 0;
  motor[right] = 0;
  eraseDisplay();
  if(found == FOUND_NODE) {
    nxtDisplayCenteredTextLine(3, "Segment end");
  }
  else if(found == FOUND_CAN) {
    nxtDisplayCenteredTextLine(3, "Can Detected");
  }
  else if(FOUND_ERROR) {
    nxtDisplayCenteredTextLine(3, "Error");
  }

  wait10Msec(1000);
}
