#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "follow_line.c"
#include "compass.c"
#include "branch_count.c"
#include "map.c"

task main() {
  calibrateLight();
  calibrateCompass();


  Edge edge;
  turnToLine();
  int found = FollowSegmentTilEnd(edge);
  int branchCount = 0;
  if(found==FOUND_NODE){

      branchCount = countBranches();
  }
  motor[left] = 0;
  motor[right] = 0;
  eraseDisplay();
  nxtDisplayCenteredTextLine(3, "no. of branches=");
  nxtDisplayCenteredTextLine(4, "%i", branchCount);
  wait10Msec(1000);
}
