#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard

#include "config.h"
#include "follow_line.c"
#include "compass.c"
#include "branch_count.c"
#include "types.h"
#include "stack.c"
#include "graph.c"
#include "exploreGraph.c"

task main(){
  calibrateLight();
  calibrateCompass();
  ExploreStack stack;
  Graph graph;

  initStack(stack);
  initGraph(graph);
  Stub stub;

  int currentNode;
  //go to node
  currentNode = exploreCurEdge(graph, stack, -1);
  //while not empty
  while(!empty(stack)){
    pop(stack, stub);
    goToNode(graph, currentNode, stub.node);
    turnToAngle(stub.angle);
    turnToLine();
    exploreCurEdge(graph, stack, -1);
  }
}
