#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "follow_line.c"
#include "compass.c"
#include "light_sensor.c"


task main() {
  calibrateLight();
  calibrateCompass();
  wait10Msec(100);
  turnToLine();
  int found = FOUND_ERROR;
  while(found != FOUND_HOTEL) {
    found = FollowSegmentTilEnd();
	  motor[left] = 0;
	  motor[right] = 0;
  }

  motor[left] = 0;
  motor[right] = 0;
  eraseDisplay();
  PlaySound(soundBeepBeep);
  nxtDisplayCenteredTextLine(3, "At the hotel");
  wait10Msec(1000);

  turnToLine();
  FollowLineTilLeaf();
  PlaySound(soundBeepBeep);
  nxtDisplayCenteredTextLine(3, "At the jetty end");
  wait10Msec(1000);
}
