#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "follow_line.c"
#include "compass.c"
#include "light_sensor.c"

#include "string_distance.c"

task main(){
  bool atOriginal = false;
  while(!atOriginal){
    //find hotel
    int hotel = FollowLineTilHotel();
    //make map
    int jetty = FollowLineTilLeaf();
    //Check if same as map 1
    //Travel
  }
}
