#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void panic(string text) {
  motor[left] = 0;
  motor[right] = 0;
  PlaySound(soundException);
  //eraseDisplay();
  nxtDisplayCenteredTextLine(1, text);
  wait10Msec(1000);
  StopAllTasks();
}
