#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "config.h"
#include "compass.c"
#include "light_sensor.c"

#define CENTRE_THRESHOLD 4
#define SWEEP_ANGLE 5

#define LEFT false
#define RIGHT true
bool followingEdge = true;
bool inSafetyZone(int centre, int threshold) {
	int diff = angleDifference(currentDirection(), centre);
	return abs(diff) > threshold;
}


bool DetectCan(void) {
 return false;
}

int CountNodeEdges(void) {
  return 0;
}

void edgeFollow(bool& running){
	motor[left] = -SPEED;
	motor[right] = SPEED;
	bool direction = LEFT;
	bool wasDark = isDark();
	do{
		//Find border point
		if(wasDark != isDark()) {
			wasDark = isDark();
			wait10Msec(10);
			if(direction == LEFT) {
				direction = RIGHT;
				motor[left] = SPEED;
				motor[right] = 0;
			} else if( direction == RIGHT) {
				direction = LEFT;
				motor[right] = SPEED;
				motor[left] = 0;
			}
		}
	}while(running);
}

task FollowEdge(){
	followingEdge = true;
	edgeFollow(followingEdge);
}
void FollowLineTilEnd(void) {
	StartTask(FollowEdge);
	wait10Msec(500);
	followingEdge = false;
}
