#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "follow_line.c"
#include "compass.c"
#include "light_sensor.c"

task main() {
  TFileHandle calibFile;
  TFileIOResult result;
  int size = 2;
  string name = "greyCalib.dat";
  Delete(name, result);
  OpenWrite(calibFile, result, name, size);
  short grey = getGreyValue();
  WriteShort(calibFile, result, grey);
  Close(calibFile, result);
  wait10Msec(1000);
}
