#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)

//*!!Code automatically generated by 'ROBOTC' configuration wizard

#include "types.h"
#include "config.h"
#include "compass.c"

void initGraph(Graph & graph){
  memset(graph.adjacency, 0, sizeof(Edge)*MAX_NODES*MAX_NODES);
  graph.nNodes = 0;
}

void addEdge(Graph & graph, int from, int to, Edge & edge){
  graph.adjacency[from][to] = edge;
  Edge reverse;
  reverse.length= edge.length;
  reverse.angle = angleDifference(edge.angle, 180);
  graph.adjacency[to][from] = reverse;
};

int addNode(Graph & graph){
  return graph.nNodes++;
}

int dijkstra(Graph & graph, int from, int to, Path & path){
    int distance;

    return 0;
}
