#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "types.h"
#include "config.h"
#include "follow_line.c"

task FollowSegments(){
  Edge edge;
  for(;;){
    FollowSegmentTilEnd(edge);
    turnToLine();
    if(abs(angleDifference(currentDirection(), edge.angle+180))< 10){
      spinInDirection();
      wait10Msec(10);
      turnToLine();
    }
  }
}

int FollowLineTilHotel(void) {
  StartTask(FollowSegments);
	bool greyBuffer[8];
	int index = 0;
	for(;;) {
	  greyBuffer[ (index++) & 0x7 ] = isGrey(); //index modulo 8 (bitmask trick)
		if(isGrey()) {
			bool isAllGrey = true;
			for(int i = 0; i < 8; i++) {
			  if(!greyBuffer[i]) {
			    isAllGrey = false;
			    break;
			  }
		  }
		  if(isAllGrey) {
		    followingEdge = false;
        StopTask(FollowSegments);
		    return FOUND_HOTEL;
		  }
		 }
		wait10Msec(5);
	}
	return FOUND_ERROR;
}
