#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "config.h"


#define LIGHT_CALIB_FILE "lightCalib.dat"
int light_threshold = -1;

void saveLightFile(int minLight, int maxLight){
  TFileHandle calibFile;
  TFileIOResult result;
  int size = 4;
  string name = "lightCalib.dat";
  Delete(name, result);
  OpenWrite(calibFile, result, name, size);
  WriteShort(calibFile, result, minLight);
  WriteShort(calibFile, result, maxLight);
  Close(calibFile, result);
}

void performLightCallibration(){
  motor[left] = SPEED;
  motor[right] = -SPEED;

  time100[T1] = 0;
  int maxLight = 0;
  int minLight = 101;
  while(time100[T1]<20){
    int value = SensorValue[light];
    if(value<minLight){
      minLight = value;
    }
    if(value>maxLight){
      maxLight = value;
    }
    wait10Msec(1);
  }
    motor[left] = 0;
    motor[right] = 0;

    saveLightFile(minLight, maxLight);
    light_threshold = (maxLight + minLight)/2;
}
void readLightCalib() {
  short dark;
  short bright;
  string calibFileName = "lightCalib.dat";

  TFileHandle calibFile;
  TFileIOResult result;
  int size = 4;
  OpenRead(calibFile, result, calibFileName, size);
  ReadShort(calibFile, result, dark);
  ReadShort(calibFile, result, bright);
  Close(calibFile, result);
  light_threshold = (bright + dark)/2;
}

void calibrateLight(){
  string calibFileName = "lightCalib.dat";

  TFileHandle calibFile;
  TFileIOResult result;
  int size = 4;
  FindFirstFile(calibFile, result, calibFileName, calibFileName, size);

  if(result==0){
    readLightCalib();
  } else{
    performLightCallibration();
  }
}


bool isDark(void) {
  return SensorValue[light] < light_threshold;
}
