#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "follow_line.c"
#include "compass.c"
#include "light_sensor.c"

task main() {
  motor[left] = SPEED;
  motor[right] = -SPEED;

  time100[T1] = 0;
  while(time100[T1]<50){
    int value = SensorValue[light];
    nxtDisplayBigStringAt(50, 50, "%i", value);
  }
}
