#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"

typedef struct{
	int angle;//in degrees
	int length;//in pivots
} Edge;

typedef struct{
	Edge edges[ISLAND_SIZE];
	int length;
} Island;

typedef struct{
	int angles[MAX_BRANCHES];
} BranchAngles;

typedef struct{
	Edge adjacency[MAX_NODES][MAX_NODES];
	int nNodes;
} Graph;


typedef struct{
	int node;
	int angle;
} Stub;

typedef struct{
	Stub stubs[MAX_NODES*MAX_BRANCHES];
	int top;
} ExploreStack;

typedef struct{
	int angles[MAX_NODES];
} Path;
